[project]
name = "odoo-addons-sygel-technology-sy-web"
version = "16.0.20241125.0"
dependencies = [
    "odoo-addon-footer_extra_info_base>=16.0dev,<16.1dev",
    "odoo-addon-web_company_logo>=16.0dev,<16.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 16.0",
]
